CREATE TABLE customer(
   cust_id NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL PRIMARY KEY
  ,mail_id VARCHAR2(30)   
  ,firstname  VARCHAR2(15)
  ,lastname   VARCHAR2(15)
  ,password   VARCHAR2(15)
  ,address    VARCHAR2(100)
  ,ZipCode    INTEGER
  ,City       VARCHAR2(20)
  ,State      VARCHAR2(20) 
  ,phno       VARCHAR2(14));

CREATE TABLE restaurant(
   rest_id NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL PRIMARY KEY 
  ,rname  VARCHAR2(15)
  ,mail_id VARCHAR2(30)
  ,address    VARCHAR2(100)
  ,ZipCode    INTEGER
  ,City       VARCHAR2(20)
  ,State      VARCHAR2(20) 
  ,phno       VARCHAR2(14));

CREATE TABLE menu(
   item_id NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL PRIMARY KEY
  ,rest_id NUMBER(10)  
  ,iname  VARCHAR2(15)
  ,price   NUMBER(10,2)
  ,FOREIGN KEY (rest_id) REFERENCES restaurant(rest_id)ON DELETE CASCADE);

CREATE TABLE orders(
   order_id NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL PRIMARY KEY
  ,rest_id NUMBER(10)  
  ,cust_id NUMBER(10)
  ,subtotal NUMBER(10,2)
  ,total NUMBER(10,2)
  ,status VARCHAR2(10)
  ,otime timestamp
  ,FOREIGN KEY (rest_id) REFERENCES restaurant(rest_id) ON DELETE CASCADE
  ,FOREIGN KEY (cust_id) REFERENCES customer(cust_id)ON DELETE CASCADE);
  
CREATE TABLE orderitems(
   id NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL PRIMARY KEY
  ,order_id NUMBER(10)
  ,item_id NUMBER(10)
  ,quantity NUMBER(10)  
  ,FOREIGN KEY (item_id) REFERENCES menu(item_id)ON DELETE CASCADE
  ,FOREIGN KEY (order_id) REFERENCES orders(order_id)ON DELETE CASCADE);

CREATE TABLE reviews(
   r_id NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL PRIMARY KEY
  ,rest_id NUMBER(10)  
  ,rating NUMBER(10)
  ,review VARCHAR2(500)
  ,cust_id NUMBER(10)
  ,rtime timestamp
  ,FOREIGN KEY (rest_id) REFERENCES restaurant(rest_id)ON DELETE CASCADE
  ,FOREIGN KEY (cust_id) REFERENCES customer(cust_id)ON DELETE CASCADE);

CREATE TABLE admin( 
   admin_id NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL PRIMARY KEY 
  ,admin_mail VARCHAR2(30)
  ,firstname  VARCHAR2(15)
  ,lastname   VARCHAR2(15)
  ,password VARCHAR2(15));
  
insert into admin(admin_mail,firstname,lastname,password) values('admin@foodzilla.com','admin','admin','admin@123');
insert into customer(mail_id,firstname,lastname,password,address,zipcode,city,state,phno) values('priya@gmail.com','priya','shukla','priya@123','234 south street',56432,'chicago','illinois',3128569338);

commit;